devvsakib/power-the-web

README.md

Feature : Add a readme file [fixes #3]

---

PROJECTS/ProjectIdeas.txt

Keep it here so that we can change it if we have got a new Ideas also we can keep a track of our Ideas

Added Ideas for ReactJs Projects

---

blog.html
index.html

Completed the blog page.
This issue is linked to this [issue](https://github.com/devvsakib/hacktoberfest-react-project/issues/22)

Added the blog page

---

CONTRIBUTORS.md
blog.html
index.html
project.css
project.html

Added the project.html and project.css
Solved issue #38.
Please Merge my pull request.

Added the project.html + project.css

---

Contributors.json

added contributors.json file as per the issue #58 
The file has the format as there was shown in the issue.

added contributors.json file

---

assets/css/contributor.css
contributor.html

This PR will close this [issue](https://github.com/devvsakib/hacktoberfest-react-project/issues/61)
This PR will implement the contributors page for the project.

feat: created initial setup for contributors page

---

PROJECTS/Data-Manager/add.html
PROJECTS/Data-Manager/add.html.bak
PROJECTS/Data-Manager/delete.html
PROJECTS/Data-Manager/first1.java
PROJECTS/Data-Manager/index.html
PROJECTS/Data-Manager/index.html.bak
PROJECTS/Data-Manager/modify.html
PROJECTS/Data-Manager/modify.html.bak
PROJECTS/Data-Manager/modify1.html.bak
PROJECTS/Data-Manager/x.html
PROJECTS/Data-Manager/x.html.bak

Added a new project known as Data Manager.
By @Git-Akshat for @hacktoberfest

Data Manager

---

CONTRIBUTORS.md
PROJECTS/Data-Manager/add.html
PROJECTS/Data-Manager/add.html.bak
PROJECTS/Data-Manager/delete.html
PROJECTS/Data-Manager/first1.java
PROJECTS/Data-Manager/index.html
PROJECTS/Data-Manager/index.html.bak
PROJECTS/Data-Manager/modify.html
PROJECTS/Data-Manager/modify.html.bak
PROJECTS/Data-Manager/modify1.html.bak
PROJECTS/Data-Manager/x.html
PROJECTS/Data-Manager/x.html.bak

Added my details in the contributors list.

Added Details in the contributors list.

---

Contributors.json
contributor.html

added contributors page

---

contributor.html

Earlier the contributors cards were aligned vertically, I have made them to align horizontally.

Made contributors cards to align horizontally

---

main-website/src/App.js
main-website/src/component/Footer/Footer.js

Footer Section Completed @devvsakib

Footer Done

---

main-website/src/component/Navbar/Navbar.css
main-website/src/component/Navbar/Navbar.js
main-website/yarn.lock

This pill request will close this [issue](https://github.com/devvsakib/hacktoberfest-react-project/issues/82).
This PR will use CSS media queries to make the navigation bar follow the Responsive Web Designs. The hamburger icon will be displayed when the device resolution falls below a `640px` width.

update: implement a responsive navigation bar for React site

---

main-website/package-lock.json
main-website/package.json
main-website/src/component/Footer/Footer.js
main-website/src/component/Navbar/Navbar.js
main-website/yarn.lock

I had to redo most of the navbar since the mobile part was completely missing, and I used HeadlessUI like Tailwind uses in it's components.
Hope you like it.
(also fixed a typo in footer since it spammed my console with errors)

Fixed navbar not working on mobile, issue #91

---

Contributors.json
main-website/src/Contributors.json
main-website/src/component/Footer/Footer.js
main-website/src/component/pages/Contributors.js
main-website/tailwind.config.js

1. Added Profile Card to the covert-react ISSUE #90 ✅
2. Added My Self To the contributors.json 😊
Have a look @devvsakib

Added Profile Card Component (covert-react).

---

main-website/src/App.js
main-website/src/component/Navbar/Navbar.js
main-website/src/component/pages/Roadmap.js
main-website/yarn.lock

This pull request will close this [issue](https://github.com/devvsakib/hacktoberfest-react-project/issues/98)
This PR will add a skeleton for the roadmap page to the main-website application. It also adds the link to the roadmap page to the Navbar.

feat: create roadmap page

---

main-website/src/component/Navbar/Navbar.js

Fixed the website reloading while navigating page #114 
@devvsakib

Website Reloading While Navigating Issue Fixed

---

Contributors.json
main-website/package-lock.json
main-website/src/component/HeroSection/Herosection.js
main-website/src/component/Navbar/Navbar.js
main-website/src/json/Contributors.json
main-website/yarn.lock
package-lock.json

Hey @devvsakib I found the typo that stopped the navbar from working, #128 seems to be finally closed. Sorry for missing this out when I made the new navbar..
I didn't test properly last time and it shouldn't have got to github with this bug.

Fixed typo causing Navbar to stop working on mobile

---

main-website/src/App.js
main-website/src/component/Button/ScrollToTop.js
main-website/src/main.css

1. Implemented The Bottom-To-Top Scroll Button  #135 
2. Hide the Scrollbar For Every Browser Implemented #136 
Both #135 & #136 Have been Implemented @devvsakib

Button To Scroll To Top Feature Implemented

---

CONTRIBUTORS.md
src/component/Footer/Footer.js
src/json/Contributors.json

modified:   src/component/Footer/Footer.js
modified:   src/json/Contributors.json
modified:  CONTRIBUTORS.md

Fixed Open Issue 154, fixed CONTRIBUTORS.md not showing up correctly.

---

package-lock.json
src/component/Footer/Footer.js
src/component/HeroSection/Hero.css
src/component/HeroSection/Herosection.js
src/json/Contributors.json
yarn.lock

- Changed the **Hero title color** to the logo color
- As its **2023** the footer was not updated so I updated it
- Added me as a contributor

Changed the hero title color to logo color

---

src/json/Blogs.json
src/json/Contributors.json

I've added myself to the contributors page

Update of contributors.json

---

src/App.js
src/component/Button/ScrollToTop.js
src/component/Contributors/CProfileCard.js
src/component/Contributors/GetContributors.js
src/component/Guidelines/pages/Cards.js
src/component/Guidelines/pages/Documents.js
src/component/HeroSection/Hero.css
src/component/HeroSection/Herosection.js
src/component/pages/Contributors.js

Please feel free to review. 
You can get a Green Square by reviewing code🧩

PowerTheWeb text font size 7rem -> 5rem

---

src/component/pages/Blog.js
src/json/Blogs.json
src/json/Contributors.json
yarn.lock

Do need some clarification on Add Button on Blog Page and its styles.

Added Two Blogs, Added Title and Tagline on Blog Page and  Myself in Contributors 

---

src/component/pages/Blog.js
src/json/Blogs.json

@SalmanShahid888 added two blogs somehow while emerging we got only 1 blog. So I added missing blog

added @SalmanShahid888 's missed blog[there was some merging issue]

---

src/component/Guidelines/pages/Documents.js
src/component/Projects/GetProjects.js
src/component/pages/Blog.js
src/json/Contributors.json

doing some UI changes.
Feel free to review

UI improve

---

README.md

Hey @devvsakib 
This pull request is for the issue #213 
Let me know if this looks good to you.

Issue 213 fix title in readme

---

src/component/Error/Error.js
src/component/Projects/GetProjects.js
src/component/Projects/Projects.css
src/main.css

1. Add error component
2. Update style of project page
3. Add condition if error when load project list from github api

Add error component and update style of project page

---

src/component/Footer/Footer.js
src/main.css

producthunt badge added in the footer issue #226

---

README.md

Added product badge and centered the div

---

src/json/Contributors.json
src/json/interviewquestions.json

Added two of the most frequently asked questions on the useEffect hook.

useeffect question added

---

README.md

Issue: https://github.com/devvsakib/power-the-web/issues/241

Update repo size in README

---

package-lock.json
src/json/Contributors.json
src/json/interviewquestions.json
yarn.lock

I have added react interview question in interviewquestions.json file.

Added few interview question

---

src/json/Contributors.json
src/json/interviewquestions.json

I added react interview questions and answers

add react interview questions

---

src/json/interviewquestions.json

Questions added on the following hooks:  useReducer, useContext, useRef,  useMemo and useCallback.

more Questions on react hooks added

---

src/json/interviewquestions.json

Hi, I added in interviewquestions.json some react interview questions.

added some new react interview questions

---

src/json/interviewquestions.json

Hi. I added some html and css interview questions.

Html css interview questions

---

src/component/Guidelines/List/FrontendInterview.js
src/json/interviewquestions.json

added interview questions #259

---

basic frontend.md

Closes #265 
Hope you like it.

Created a well curated frontend roadmap for Power the web 

---

src/json/interviewquestions.json

I added new react interview question right after the last one which already existed. I can add more if important!

Added new react interwiev questions

---

src/json/Contributors.json
src/json/interview/typescript.json

I have added a question on typescript topic.

Add question on typescript

---

src/json/interview/react.json

Three questions added to the react json

Added three questions to the react json file

---

README.md

Reverts devvsakib/power-the-web#279

Revert "updated"

---

README.md

As per request  described portion of data is deleted by @devharsh007

Fix for issue #286

---

CONTRIBUTING.md

guideline updated for contributors issue #276

---

src/json/Contributors.json

I have updated the json file as you said earlier. 
Sorry for the inconvenience . 
I am new to Open Source.
--Thank you

Updating JSON

---

src/component/Guidelines/pages/Documents.js

bug: fixed theme toggle button overlapping with menu toggle button

---

src/json/Contributors.json

I have added my name to the contributors list.

added my name to the contributors list

---

src/json/Contributors.json

Hey, I have updated my profile picture in the contributor's list. Please allow me to make changes.

Updated my profile picture.

---

src/component/pages/Card.js

add docs link how to contributor card page. 
This for guide how to add project to show in contributor card

add docs link how to use contributor card page

---

docs/contributor-card.md

Hi there,
I've made some changes to the contributors.md file in order to make it easier to read and understand. I added some formatting and organization to the steps, as well as some additional motivation for contributors to join the project.
Please take a look and let me know if you have any feedback or suggestions for further improvements.
Thank you!

Updated the readability of Contributors Card

---

src/component/Blog/BlogCard.js

I added the hover effect to blog cards

added hover effect to the blog card
